<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - Golden Scene</title>
    <!-- Link to CSS files for styling -->
    <link rel="stylesheet" href="css/global.css">
    <link rel="stylesheet" href="css/index.css">
</head>
<body>
   
    <?php require_once("header.php"); ?>
    
    <?php require_once("dbinfo.php"); ?>
    <?php
    // Check if the user is logged in
    if (isset($_SESSION["user_id"])) {
        $display_name = "";

        // 1. Try to get the name from the session first
        if (isset($_SESSION["username"])) {
            $display_name = $_SESSION["username"];
        } elseif (isset($_SESSION["name"])) {
             $display_name = $_SESSION["name"];
        }
        
        // 2. If not in session, fetch from database
        else {
            $uid = $_SESSION["user_id"];
            // We use 'fullname' based on your previous code
            $user_result = $mysqli->query("SELECT fullname FROM users WHERE user_id = '$uid'");
            
            if ($user_result && $u_row = $user_result->fetch_assoc()) {
                $display_name = $u_row['fullname']; 
            }
        }

        // Display the premium banner
        if (!empty($display_name)) {
            echo '<div class="user-welcome-banner">';
            echo '  <div class="welcome-content">';
            echo '    <span class="greeting">Hello,</span>';
            echo '    <span class="username">' . htmlspecialchars($display_name) . '</span>';
            echo '  </div>';
            echo '</div>';
        }
    }
    ?>


    <?php
    // Get latest movies for hero slider - ordered by newest release date first
    $slider_result = $mysqli->query("SELECT * FROM movies ORDER BY release_date DESC");
    ?>

    <main>
        <!-- Hero slider section - displays movie banners in rotating slideshow -->
        <section class="hero-slider">
            
            <div class="slider-container">
                <?php
                // Display movies in hero slider with booking links
                if ($slider_result && $slider_result->num_rows > 0):
                    while ($movie = $slider_result->fetch_assoc()):
                        // Set banner image path - use movie banner or fallback to placeholder
                        $banner = $movie['banner_url'] ? 'images/' . htmlspecialchars($movie['banner_url']) : 'images/placeholder.png';
                        $title = htmlspecialchars($movie['title']);
                        $movie_id = $movie['movie_id'];
                ?>
                <!-- Individual slide with movie data - each slide contains movie info for jQuery -->
                <div class="slide" data-movie-id="<?php echo $movie_id; ?>" data-movie-title="<?php echo $title; ?>">
                    <a href="movie_booking.php?movie_id=<?php echo $movie_id; ?>">
                        <img src="<?php echo $banner; ?>" alt="<?php echo $title; ?>" class="slider-image fit-cover">
                    </a>
                </div>
                <?php endwhile;
                else: ?>
                <!-- Fallback slide when no movies are available -->
                <div class="slide" data-title="No Movies">
                    <img src="images/placeholder.png" alt="No Movies" class="slider-image fit-cover">
                </div>
                <?php endif; ?>
            </div>
            
            <!-- Slider navigation arrows - left and right buttons -->
            <div class="slider-nav">
                <button class="prev-slide" aria-label="Previous slide">❮</button>
                <button class="next-slide" aria-label="Next slide">❯</button>
            </div>
            
            <!-- Quick book button - allows users to book tickets for current slide -->
            <div class="buy-now-container">
                <button class="buy-now" id="book-tickets-btn">Book Tickets Now</button>
            </div>
            
            <!-- Slider dots - navigation indicators (generated by jQuery) -->
            <div class="slider-dots">
                
            </div>
        </section>

        <!-- Quick buy section - simplified booking form -->
        <section class="quick-buy">
            <h1 class="page-title">Quick Buy</h1>
            <div class="quick-buy-card">
            <form action="choose_seat.php" method="GET" class="quick-buy-form" id="quick-buy-form">
                <div class="quick-buy-row">
                    <label for="quick-buy-date">Date</label>
                    <select name="selected_date" id="quick-buy-date" required>
                        <option value="" disabled selected>Date</option>
                        <?php
                        // Generate date options for next 7 days - starting from today
                        for ($i = 0; $i < 7; $i++) {
                            $date = date('Y-m-d', strtotime("+$i days"));
                            $label = date('D, M j', strtotime($date));
                            echo "<option value=\"$date\">$label</option>";
                        }
                        ?>
                    </select>
                </div>
                <div class="quick-buy-row">
                    <label for="quick-buy-movie">Movie</label>
                    <select name="movie_id" id="quick-buy-movie" required>
                        <option value="" disabled selected>Select Movie</option>
                        <?php
                        // Populate movie dropdown from database - ordered by newest first
                        $movie_result = $mysqli->query("SELECT movie_id, title FROM movies ORDER BY release_date DESC");
                        if ($movie_result && $movie_result->num_rows > 0) {
                            while ($m = $movie_result->fetch_assoc()) {
                                $mid = $m['movie_id'];
                                $mtitle = htmlspecialchars($m['title']);
                                echo "<option value=\"$mid\">$mtitle</option>";
                            }
                        }
                        ?>
                    </select>
                </div>
                <div class="quick-buy-row">
                    <label for="quick-buy-theatre">Theatre</label>
                    <select name="selected_theater" id="quick-buy-theatre" required>
                        <option value="" disabled selected>Select Theatre</option>
                        <?php
                        // Theatre selection options - ordered alphabetically
                        $theatre_result = $mysqli->query("SELECT theater_id, name FROM theaters ORDER BY name");
                        if ($theatre_result && $theatre_result->num_rows > 0) {
                            while ($t = $theatre_result->fetch_assoc()) {
                                $tid = $t['theater_id'];
                                $tname = htmlspecialchars($t['name']);
                                echo "<option value=\"$tid\">$tname</option>";
                            }
                        }
                        ?>
                    </select>
                    <!-- Hidden field to store theatre name for form submission -->
                    <input type="hidden" name="selected_theater_name" id="quick-buy-theatre-name" value="">
                </div>
                <div class="quick-buy-row">
                    <label for="quick-buy-time">Showtime</label>
                    <select name="selected_time" id="quick-buy-time" required>
                        <option value="" disabled selected>Select Time</option>
                        <!-- Fixed showtime options -->
                        <option value="10:00 AM">10:00 AM</option>
                        <option value="12:00 PM">12:00 PM</option>
                        <option value="3:10 PM">3:10 PM</option>
                        <option value="6:30 PM">6:30 PM</option>
                        <option value="9:50 PM">9:50 PM</option>
                    </select>
                </div>
            </form>
            <!-- Form action buttons -->
            <div class="form-buttons">
                <button type="reset" class="reset-btn" form="quick-buy-form">Reset</button>
                <button type="submit" class="confirm-btn" form="quick-buy-form">Confirm</button>
            </div>
            </div>
        </section>

        <!-- Movie showtimes section - displays all movies with pagination -->
        <section class="movie-showtimes">
            <div class="container">
                <h1 class="page-title">Movie Showtimes</h1>
                <?php
                // Pagination and filtering settings
                $movies_per_page = 9; // Number of movies to show per page
                $current_page = isset($_GET['page']) ? (int)$_GET['page'] : 1; // Get current page from URL
                $current_status = isset($_GET['status']) ? $_GET['status'] : 'now_showing'; // Get movie status filter
                
                // Get all movies from database and group them by status
                $all_movies = [];
                $result = $mysqli->query("SELECT * FROM movies ORDER BY release_date DESC");
                if ($result && $result->num_rows > 0) {
                    while ($movie = $result->fetch_assoc()) {
                        $all_movies[$movie['status']][] = $movie;
                    }
                }
                
                // Movie status options for filtering tabs
                $statuses = [
                    'now_showing' => 'Now Showing',
                    'coming_soon' => 'Coming Soon',
                    'advance_sale' => 'Advance Sale'
                ];
                
                // Calculate pagination values
                $current_movies = $all_movies[$current_status] ?? []; // Get movies for current status
                $total_pages = ceil(count($current_movies) / $movies_per_page); // Calculate total pages needed
                $current_page = max(1, min($current_page, $total_pages)); // Ensure current page is valid
                $current_page_movies = array_slice($current_movies, ($current_page - 1) * $movies_per_page, $movies_per_page); // Get movies for current page
                ?>
                <!-- Status filter tabs - allow users to switch between movie categories -->
                <div class="tabs">
                    <?php foreach ($statuses as $key => $label): ?>
                        <a href="?status=<?php echo $key; ?>&page=1" 
                           class="tab<?php echo $key === $current_status ? ' active' : ''; ?>" 
                           data-status="<?php echo $key; ?>"><?php echo $label; ?></a>
                    <?php endforeach; ?>
                </div>
                <!-- Movie grid display - shows movies in card format -->
                <div class="movie-grid">
                    <?php if (!empty($current_page_movies)): ?>
                        <?php foreach ($current_page_movies as $movie):
                            // Set poster image path - use movie poster or fallback to placeholder
                            $poster = $movie['poster_url'] ? 'images/' . htmlspecialchars($movie['poster_url']) : 'images/placeholder.png';
                        ?>
                        <!-- Movie card - individual movie display with poster and booking button -->
                        <div class="movie-card">
                            <div class="movie-poster-container">
                                <a href="movie_booking.php?movie_id=<?php echo $movie['movie_id']; ?>">
                                    <img src="<?php echo $poster; ?>" alt="<?php echo htmlspecialchars($movie['title']); ?> Poster" class="movie-poster fit-cover">
                                </a>
                            </div>
                            <div class="movie-info">
                                <h3><?php echo htmlspecialchars($movie['title']); ?></h3>
                                <a href="movie_booking.php?movie_id=<?php echo $movie['movie_id']; ?>" class="btn btn-primary book-now">Book Now</a>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <!-- No movies message - displayed when no movies match current filter -->
                        <p style="grid-column:1/-1;text-align:center;">No movies found.</p>
                    <?php endif; ?>
                </div>
                
                <!-- Pagination navigation - allows users to browse through pages -->
                <?php if ($total_pages > 1): ?>
                <div class="pagination">
                    <!-- Previous page link - only show if not on first page -->
                    <?php if ($current_page > 1): ?>
                        <a href="?status=<?php echo $current_status; ?>&page=<?php echo $current_page - 1; ?>" class="page-link">&laquo; Previous</a>
                    <?php endif; ?>
                    
                    <!-- Page number links - show all available pages -->
                    <?php for ($i = 1; $i <= $total_pages; $i++): ?>
                        <?php if ($i == $current_page): ?>
                            <!-- Current page - highlighted and not clickable -->
                            <span class="page-link active"><?php echo $i; ?></span>
                        <?php else: ?>
                            <!-- Other pages - clickable links -->
                            <a href="?status=<?php echo $current_status; ?>&page=<?php echo $i; ?>" class="page-link"><?php echo $i; ?></a>
                        <?php endif; ?>
                    <?php endfor; ?>
                    
                    <!-- Next page link - only show if not on last page -->
                    <?php if ($current_page < $total_pages): ?>
                        <a href="?status=<?php echo $current_status; ?>&page=<?php echo $current_page + 1; ?>" class="page-link">Next &raquo;</a>
                    <?php endif; ?>
                </div>
                <?php endif; ?>
            </div>
        </section>

        <!-- Sign up/login section - only shown to non-logged in users -->
        <?php if (!isset($_SESSION["user_id"])): ?>
        <section class="dont-miss-out">
            <h2><span aria-hidden="true" class="dont-miss-out-icon">🎬</span> Don't Miss Out!</h2>
            <p class="dont-miss-out-text">Sign up now to get the latest movies, exclusive offers, and more.</p>
            <div class="cta-buttons">
                <form action="signup.php" method="get">
                    <button type="submit" class="signup-btn">Sign Up</button>
                </form>
                <form action="login.php" method="get">
                    <button type="submit" class="login-btn">Login</button>
                </form>
            </div>
        </section>
        <?php endif; ?>
    </main>

    <!-- Include footer -->
    <?php require_once("footer.php"); ?>

    <!-- jQuery script section - handles all interactive functionality -->
    <script>
    // Hero slider functionality - creates rotating slideshow of movie banners
    $(document).ready(function() {
        // Initialize slider variables
        let currentIndex = 0; // Track current slide position
        const slides = $('.slide'); // Get all slide elements
        const totalSlides = slides.length; // Count total number of slides
        let slideInterval; // Timer for auto-sliding

        // Generate navigation dots dynamically - one dot per slide
        const $sliderDots = $('.slider-dots');
        $sliderDots.empty(); // Clear existing dots
        for (let i = 0; i < totalSlides; i++) {
            $sliderDots.append('<span class="dot"></span>'); // Add dot for each slide
        }
        
        // Show first slide and activate first dot
        slides.first().addClass('active').show(); // Display first slide
        $('.dot').first().addClass('active'); // Highlight first dot

        // Function to display a specific slide by index
        function showSlide(index) {
            slides.removeClass('active').hide(); // Hide all slides
            slides.eq(index).addClass('active').show(); // Show selected slide
            $('.dot').removeClass('active').eq(index).addClass('active'); // Update dot states
        }

        // Function to change slide with circular navigation (wraps around)
        function changeSlide(step) {
            currentIndex = (currentIndex + step + totalSlides) % totalSlides; // Calculate new index with wrap-around
            showSlide(currentIndex); // Display the new slide
        }

        // Start auto-slide timer - changes slide every 5 seconds
        function startAuto() {
            stopAuto(); // Clear any existing timer first
            slideInterval = setInterval(function() { 
                changeSlide(1); // Move to next slide
            }, 5000); // 5 second interval
        }

        // Stop auto-slide timer
        function stopAuto() {
            if (slideInterval) {
                clearInterval(slideInterval); // Clear the timer
                slideInterval = null; // Reset timer variable
            }
        }

        // Event handlers for user interaction
        $('.next-slide').click(function() { 
            changeSlide(1); // Move to next slide when next button clicked
        });

        $('.prev-slide').click(function() { 
            changeSlide(-1); // Move to previous slide when prev button clicked
        });

        // Dot navigation - allow users to jump to specific slides
        $sliderDots.on('click', '.dot', function() {
            currentIndex = $(this).index(); // Get clicked dot index
            showSlide(currentIndex); // Show corresponding slide
        });

        // Start auto-slide functionality
        startAuto();

        // Pause auto-slide when user hovers over slider
        $('.hero-slider').hover(
            function() { 
                stopAuto(); // Stop sliding when mouse enters
            }, 
            function() { 
                startAuto(); // Resume sliding when mouse leaves
            }
        );

        // Quick booking functionality - book tickets for currently displayed movie
        $('#book-tickets-btn').click(function() {
            const movieId = $('.slide.active').data('movie-id'); // Get movie ID from active slide
            // Redirect to booking page for current movie, or movies page if no movie selected
            window.location.href = movieId ? 'movie_booking.php?movie_id=' + movieId : 'movies.php';
        });

        // Update hidden theatre name field when theatre selection changes
        $('#quick-buy-theatre').on('change', function() {
            // Store the selected theatre name in hidden field for form submission
            $('#quick-buy-theatre-name').val($(this).find('option:selected').text());
        });
    });
    </script>
</body>
</html>